export const PATH_URL_DATA = {
  urlLogin: 'auth/sign-in',
  urlHome: 'novit/home',
  urlUserList: 'novit/user/list',
  urlUserDetail: 'novit/user/detail/',
  urlAccount: 'register',
  urlVerify: 'auth/email-verify',
  urlTask: 'task',
  urlProject: 'project',
  urlUsuarios: 'usuarios',
  urlPeriodos: 'periodos',
  urlBandejaVacaciones: 'bandeja',
  urlRegistrarVacaciones: 'registrar',
  urlReporte: 'reporte',
  urlReporteHistorico: 'reporte-historico',
  urlReporteSolicitudes: 'reporte-solicitudes',
  urlDetalleVacaciones: 'solicitud/:solic',
  urlInterrupcionVacaciones: 'interrumpir-solicitud/:solic',
  urlReprogramarVacaciones: 'reprogramar-solicitud/:solic',
  urlSolicitudesPendientes: 'solicitudes-pendientes',
  urlSolicitudesPendientesDetalle: 'solicitudes-pendientes/:solic',
  urlSolicitudesPendientesGrh: 'solicitudes-pendientes-grh',
  urlSolicitudesPendientesDetalleGrh: 'solicitudes-pendientes-grh/:solic',
  urlValidarDocumento: 'valida-documento/:documento',
  ulrError: 'error',
  urlDefault: '',
  urlDefault2: '**',
};
